apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dpcdom

resources:
  - ../../base

patches:
  - path: data-pvc-patch.yaml
  - path: postgresql-patch.yaml
  - path: web-initial-patch.yaml

images:
  - name: ghcr.io/ritareasciencepark/dpc_fam_and_struct_webapp
    newTag: replace-with-git-sha

  - name: ghcr.io/ritareasciencepark/dpc_fam_and_struct_webapp-data-loader
    newTag: replace-with-git-sha
