# Generated by Django 6.0.1 on 2026-07-16 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dpcstruct', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dpcstructcath',
            options={'managed': False, 'verbose_name': 'DPCstruct CATH Annotation', 'verbose_name_plural': 'DPCstruct CATH Annotations'},
        ),
        migrations.AlterModelOptions(
            name='dpcstructmcsproperty',
            options={'managed': False, 'verbose_name': 'DPCstruct MC Properties and Pfam Annotations', 'verbose_name_plural': 'DPCstruct MC Properties and Pfam Annotations'},
        ),
        migrations.AlterModelOptions(
            name='dpcstructmcssequence',
            options={'managed': False, 'verbose_name': 'DPCstruct MC Seed Sequence', 'verbose_name_plural': 'DPCstruct MC Seed Sequences'},
        ),
        migrations.AlterModelOptions(
            name='dpcstructscop',
            options={'managed': False, 'verbose_name': 'DPCstruct SCOP Annotation', 'verbose_name_plural': 'DPCstruct SCOP Annotations'},
        ),
    ]
