# Generated by Django 6.0.1 on 2026-07-16 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dpc', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dpcuniref50pfam',
            options={'managed': False, 'verbose_name': 'DPC UniRef50 Pfam Mapping', 'verbose_name_plural': 'DPC UniRef50 Pfam Mappings'},
        ),
    ]
