# Generated by Django 6.0.1 on 2026-07-16 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dpcfam', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dpcfammcsproperty',
            options={'managed': False, 'verbose_name': 'DPCfam MC Properties and Pfam Annotations', 'verbose_name_plural': 'DPCfam MC Properties and Pfam Annotations'},
        ),
        migrations.AlterModelOptions(
            name='dpcfammcssequence',
            options={'managed': False, 'verbose_name': 'DPCfam MC Seed Sequence', 'verbose_name_plural': 'DPCfam MC Seed Sequences'},
        ),
    ]
