apiVersion: v1
kind: ConfigMap
metadata:
  name: dpcexplorer-config
data:
  DEBUG: "False"
  LOG_LEVEL: "INFO"

  DPC_DATA_ROOT: "/data"
  DPCEXPLORER_ADMIN_WRITABLE: "False"

  DB_HOST: "dpcexplorer-postgresql-rw"
  DB_PORT: "5432"
  DB_NAME: "dpcexplorer"
  DB_USER: "dpcexplorer_app"

  ALLOWED_HOSTS: "127.0.0.1,localhost"
  CSRF_TRUSTED_ORIGINS: ""

  TRUST_X_FORWARDED_PROTO: "False"
  SECURE_SSL_REDIRECT: "False"
  SESSION_COOKIE_SECURE: "False"
  CSRF_COOKIE_SECURE: "False"
  SECURE_HSTS_SECONDS: "0"
  SECURE_HSTS_INCLUDE_SUBDOMAINS: "False"
  SECURE_HSTS_PRELOAD: "False"
